export const trophies = [
    '',
    'Sans',
    'Civil Rights',
    'Economy',
    'Political Freedoms',
    'Population',
    'Wealth Gaps',
    'Death Rate',
    'Compassion',
    'Eco Friendliness',
    'Social Conservatism',
    'Nudity',
    'Automobile Manufacturing',
    'Cheese Exports',
    'Basket Weaving',
    'Informtion Technology',
    'Pizza Delivery',
    'Trout Fishing',
    'Arms Manufacturing',
    'Agriculture',
    'Beverage Sales',
    'Timber Woodchipping',
    'Mining',
    'Insurance',
    'Furniture Restoration',
    'Retail',
    'Book Publishing',
    'Gambling',
    'Manufacturing',
    'Government Size',
    'Welfare',
    'Public Healthcare',
    'Law Enforcement',
    'Business Subsidization',
    'Religiousness',
    'Income Equality',
    'Niceness',
    'Rudeness',
    'Intelligence',
    'Ignorance',
    'Political Apathy',
    'Health',
    'Cheerfulness',
    'Weather',
    'Compliance',
    'Safety',
    'Lifespan',
    'Ideological Radicality',
    'Defense Forces',
    'Pacifism',
    'Economic Freedom',
    'Taxation',
    'Freedom From Taxation',
    'Corruption',
    'Integrity',
    'Authoritarianism',
    'Youth Rebelliousness',
    'Culture',
    'Employment',
    'Public Transport',
    'Tourism',
    'Weaponization',
    'Recreational Drug Use',
    'Obesity',
    'Secularism',
    'Environmental Beauty',
    'Charmlessness',
    'Influence',
    'World Assembly Endorsements',
    'Averageness',
    'Human Development Index',
    'Primitiveness',
    'Scientific Advancement',
    'Inclusiveness',
    'Average Income',
    'Average Income Of Poor',
    'Average Income Of Rich',
    'Public Education',
    'Economic Output',
    'Crime',
    'Foreign Aid',
    'Black Market',
    'Residency',
    'Average Disposable Income',
    'International Artwork',
    'Food Quality',
    'Patriotism'
  ]

export const governments = [
  'Anarchy',
  'Authoritarian Democracy',
  'Benevolent Dictatorship',
  'Capitalist Paradise',
  'Capitalizt',
  'Civil Rights Lovefest',
  'Compulsory Consumerist State',
  'Conservative Democracy',
  'Corporate Bordello',
  'Corporate Police State',
  'Corrupt Dictatorship',
  'Democratic Socialists',
  'Father Knows Best State',
  'Free-Market Paradise',
  'Inoffensive Centrist Democracy',
  'Iron Fist Consumerists',
  'Iron Fist Socialists',
  'Left-Leaning College State',
  'Left-wing Utopia',
  'Liberal Democratic Socialists',
  'Libertarian Police State',
  'Moralistic Democracy',
  'New York Times Democracy',
  'Psychotic Dictatorship',
  'Right-wing Utopia',
  'Scandinavian Liberal Paradise',
  'Tyranny by Majority'
]
export const flags = [
  'Aaland Islands',
  "Afghanistan",
  "Albania",
  "Alderney",
  "Algeria",
  "American_Samoa",
  "Andalusia",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antigua_and_Barbuda",
  "Aragon",
  "Argentina",
  "Armenia",
  "Aruba",
  "Asturias",
  "Austral_Islands",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Azores",
  "Bahamas",
  "Bahrain",
  "Balearic_Islands",
  "Bangladesh",
  "Barbados",
  "Basque_Country",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bonaire",
  "Bosnia_and_Herzegovina",
  "Botswana",
  "Brazil",
  "British_Antarctic_Territory",
  "British_Indian_Ocean_Territory",
  "British_Virgin_Islands",
  "Brunei",
  "Bulgaria",
  "Burkina_Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Canary_Islands",
  "Cantabria",
  "Cape_Verde",
  "Castile_and_Leon",
  "Castilla-La_Mancha",
  "Catalonia",
  "Cayman_Islands",
  "Central_African_Republic",
  "Ceuta",
  "Chad",
  "Chile",
  "China",
  "Christmas_Island",
  "Chuuk",
  "Cocos_Islands",
  "Colombia",
  "Comoros",
  "Cook_Islands",
  "Costa_Rica",
  "Cote_d'Ivoire",
  "Croatia",
  "Cuba",
  "Curacao",
  "Cyprus",
  "Czech_Republic",
  "Default",
  "Democratic_Republic_of_the_Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican_Republic",
  "East_Timor",
  "Ecuador",
  "Egypt",
  "El_Salvador",
  "England",
  "Equatorial_Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Europe",
  "Extremadura",
  "Falkland_Islands",
  "Faroe_Islands",
  "Federated_States_of_Micronesia",
  "Fiji",
  "Finland",
  "France",
  "French_Polynesia",
  "Gabon",
  "Galicia",
  "Gambia",
  "Gambier_Islands",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea-Bissau",
  "Guinea",
  "Guyana",
  "Haiti",
  "Herm",
  "Honduras",
  "Hong_Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle_of_Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "La_Rioja",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Macedonia",
  "Madagascar",
  "Madeira",
  "Madrid",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marquesas_Islands",
  "Marshall_Islands",
  "Mauritania",
  "Mauritius",
  "Melilla",
  "Mexico",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Murcia",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Navarre",
  "Nepal",
  "Netherlands",
  "New_Caledonia",
  "New_Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk_Island",
  "North_Korea",
  "Northern_Mariana_Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua_New_Guinea",
  "Paraguay",
  "People's_Republic_of_China",
  "Peru",
  "Philippines",
  "Pitcairn_Islands",
  "Poland",
  "Portugal",
  "Puerto_Rico",
  "Qatar",
  "Rapa_Nui",
  "Republic_of_China",
  "Republic_of_the_Congo",
  "Romania",
  "Russia",
  "Rwanda",
  "Saba",
  "Saint-Pierre_and_Miquelon",
  "Saint_Helena",
  "Saint_Kitts_and_Nevis",
  "Saint_Lucia",
  "Saint_Vincent_and_the_Grenadines",
  "Samoa",
  "San_Marino",
  "Sao_Tome_and_Principe",
  "Sark",
  "Saudi_Arabia",
  "Scotland",
  "Sealand",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra_Leone",
  "Singapore",
  "Sint_Eustatius",
  "Sint_Maarten",
  "Slovakia",
  "Slovenia",
  "Solomon_Islands",
  "Somalia",
  "South_Africa",
  "South_Korea",
  "South_Sudan",
  "Sovereign_Military_Order_of_Malta",
  "Spain",
  "Sri_Lanka",
  "Sudan",
  "Suriname",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Tibet",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad_and_Tobago",
  "Tristan_da_Cunha",
  "Tuamotu_Archipelago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks_and_Caicos_Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United_Arab_Emirates",
  "United_Kingdom",
  "United_States_Virgin_Islands",
  "United_States_of_America",
  "Uruguay",
  "Uzbekistan",
  "Valencian_Community",
  "Vanuatu",
  "Vatican_City",
  "Venezuela",
  "Vietnam",
  "Wales",
  "West_Papua",
  "Yap",
  "Yemen",
  "Zambia",
  "Zanzibar",
  "Zimbabwe",
];
export const banners: { [key: string]: string } = {
    "Admin": "mod_status",
    "Game Mod": "mod_status",
    "WA": "wa_status",
    "Delegate": "wa_status",
    "Secretariat": "wa_status",
    "Issues Editor": "semimod_status",
    "Roleplay Mentor": "mentor_status",
    "Class": "class_status"
}
export const badges = [
    '',
    'Sans',
    'Admin',
    'Class',
    'Commended',
    'Condemned',
    'Delegate',
    'Easter Egg',
    'Forum Mod',
    'Founder',
    'Game Mod',
    'General Assembly Resolution Author',
    'Security Council Resolution Author',
    'Historical Resolution Author',
    'Issues Author',
    'Issues Editor',
    'Moderator',
    'Postmaster',
    'Postmaster General',
    'Retired Moderator',
    'Roleplay Mentor',
    'Sec Gen',
    'Secretariat',
    'Site Supporter',
    'WA'
]
export const badgesDict: { [key: string]: string } = {
    "Founder": "founder",
    "Retired Moderator": "modex",
    "Easter Egg": "eegg1",
    "Issues Author": "issuesauthor",
    "Postmaster": "acc_supporter_silver",
    "Postmaster-General": "acc_supporter",
    "Historical Resolution Author": "resauthorun",
    "General Assembly Resolution Author": "resauthorga",
    "Moderator": "mod",
    "Site Supporter": "acc_supporter_bronze"
}
export const trophiesDict: {[key: string]: string} = {
    'wealth gaps': 'wealthgaps',
    'international artwork': 'deck',
    'average income of rich': 'richincome',
    'beverage sales': 'soda',
    'freedom from taxation': 'lowtax',
    'gambling': 'gambling',
    obesity: 'fat',
    'average disposable income': 'dispincome',
    'death rate': 'death',
    weaponization: 'armed',
    'insurance': 'insurance',
    'automobile manufacturing': 'auto',
    crime: 'crime',
    charmlessness: 'avoided',
    'pizza delivery': 'pizza',
    'retail': 'retail',
    corruption: 'corrupt',
    'cheese exports': 'cheese',
    'basket weaving': 'basket',
    'furniture restoration': 'furniture',
    'political apathy': 'apathetic',
    'average income': 'income',
    rudeness: 'rude',
    'economic output': 'gdp',
    economy: 'economy',
    'scientific advancement': 'advanced',
    'youth rebelliousness': 'rebelyouth',
    'timber woodchipping': 'timber',
    'mining': 'mining',
    'sector: manufacturing': 'manufacturing',
    culture: 'culture',
    'sector: agriculture': 'agriculture',
    'book publishing': 'publishing',
    'information technology': 'tech',
    intelligence: 'smart',
    employment: 'employed',
    'arms manufacturing': 'arms',
    'business subsidization': 'business',
    nudity: 'nude',
    population: 'population',
    'government size': 'govt',
    secularism: 'godforsaken',
    'black market': 'blackmarket',
    'economic freedom': 'pro-market',
    'world assembly endorsements': 'endorsed',
    'public education': 'educated',
    'human development index': 'hdi',
    'ideological radicality': 'extreme',
    'recreational drug use': 'drugs',
    'trout fishing': 'fish',
    'social conservatism': 'conservative',
    'public healthcare': 'healthcare',
    'foreign aid': 'aid',
    authoritarianism: 'authoritarian',
    'civil rights': 'liberal',
    'political freedoms': 'polifree',
    averageness: 'average',
    influence: 'influence',
    residency: 'stationary',
    patriotism: 'patriotism',
    'average income of poor': 'poorincome',
    religiousness: 'devout',
    'public transport': 'publictransport',
    'defense forces': 'defense',
    ignorance: 'stupid',
    inclusiveness: 'inclusive',
    'food quality': 'foodquality',
    'law enforcement': 'police',
    primitiveness: 'primitive',
    pacifism: 'peace',
    cheerfulness: 'happy',
    niceness: 'nice',
    compassion: 'compassionate',
    welfare: 'welfare',
    integrity: 'leastcorrupt',
    'eco friendliness': 'eco-govt',
    tourism: 'tourism',
    'environmental beauty': 'environment',
    compliance: 'lowcrime',
    taxation: 'hightax',
    safety: 'safe',
    weather: 'weather',
    health: 'healthy',
    lifespan: 'life',
    'income equality': 'equality',
    'sans': 'no_badge'
};
export const rarityOrder: {[key: string]: number} = {
  common: 1,
  uncommon: 2,
  rare: 3,
  'ultra-rare': 4,
  epic: 5,
  legendary: 6
};