name: Deploy

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - 'backend/**'
  pull_request:
    branches: [main]
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy project
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
        port: ${{ secrets.PORT }}
        script: |
          cd actioncardqueries
          git pull origin main
          git status
          docker-compose stop web
          docker-compose rm -f web
          docker rmi actioncardqueries_web:latest
          docker-compose up -d --build